sudo: required

language: node_js
node_js:
- 'lts/*'

services:
  - docker

install:
  - make build

script:
  - make test

after_success:
  - make push
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make login;
      make deploy;
    fi
